#include <iostream>

#include <stdio.h>
#include <stdint.h>
#include <assert.h>

#include "application.h"

#include "logger.h"

#ifndef PG_MINIMAL_BUILD
#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#include <SDL2/SDL.h>
#include <SDL_opengles2.h>
#include <GLES2/gl2.h>
#else
#ifdef __linux__
#include <SDL2/SDL.h>
#include <SDL2/SDL_opengl.h>
#elif _WIN32
#include <SDL.h>
#include <SDL_opengl.h>
#endif
#include <GL/gl.h>
#endif
#endif // PG_MINIMAL_BUILD

/**
 * PgInterpreter: same command-line surface as PgCompiler, but every script
 * is compiled through the AST front-end (AstCompiler) instead of the
 * single-pass Pratt compiler. Any script PgCompiler can run should behave
 * identically here; divergences are front-end bugs.
 */
int main(int argc, char *argv[])
{
    // Decouple C++ and C stream for faster runtime
    std::ios_base::sync_with_stdio(false);

#ifdef __EMSCRIPTEN__
    printf("Starting program...\n");
#endif

    std::string fileName;
    bool enableProfiling = false;

    // Parse command line arguments
    for (int i = 1; i < argc; i++)
    {
        std::string arg = argv[i];

        if (arg == "--profile" || arg == "-p")
        {
            enableProfiling = true;
        }
        else if (arg == "--help" || arg == "-h")
        {
            std::cout << "Usage: " << argv[0] << " [options] <script.pg>" << std::endl;
            std::cout << "Runs PgScript through the AST front-end (AstCompiler)." << std::endl;
            std::cout << "Options:" << std::endl;
            std::cout << "  --profile, -p    Enable profiling" << std::endl;
            std::cout << "  --compile-only, -c  Compile the script without executing" << std::endl;
            std::cout << "  --help, -h       Show this help message" << std::endl;
            std::cout << "  --info, -i       Show info logs" << std::endl;
            std::cout << "  --generated-bytecode, -gb  Output generated bytecode to a file" << std::endl;
            std::cout << "  --O0, -O1, -O2, -O3  Set optimization level (default: O3)" << std::endl;
            return 0;
        }
        else if (fileName.empty())
        {
            fileName = arg;
        }
    }

    InterpreterApp app(fileName, enableProfiling, argc, argv);

    return app.exec();
}
