#pragma once

#include "ECS/system.h"
#include "Systems/coresystems.h"
#include "Input/inputcomponent.h"   // for OnSDLMouseMotion

namespace pg
{
    class MasterRenderer;
    class Input;
    class Window;

    /**
     * Simple fly-through FPS camera controller.
     *
     *   WASD           — move forward/back/strafe in the view plane
     *   Space / LShift — move up / down along world Y
     *   Mouse          — rotate the view (yaw/pitch); cursor is locked to the
     *                    window by default so no button needs to be held
     *   LAlt (hold)    — release the cursor temporarily
     *
     * The controller writes directly to `MasterRenderer::camera`, which is
     * then read by the engine when building the `view` uniform for viewport 0.
     */
    struct Camera3DController : public System<InitSys, Listener<TickEvent>, Listener<OnSDLMouseMotion>>
    {
        Camera3DController(MasterRenderer* masterRenderer, const Input* input, Window* window);

        std::string getSystemName() const override { return "Camera 3D Controller"; }

        void init() override;

        void onEvent(const TickEvent& event) override;
        void onEvent(const OnSDLMouseMotion& event) override;

        // Tunables
        float moveSpeed  = 0.01f;    // world units per millisecond (TickEvent::tick is in ms)
        float mouseSens  = 0.15f;    // degrees / pixel

        // Set by EditorSystem on Tab: when true the controller yields cursor
        // and look control to the editor, but still allows WASD movement.
        bool editMode = false;

    private:
        MasterRenderer* masterRenderer = nullptr;
        const Input*    input          = nullptr;
        Window*         window         = nullptr;

        // Current cursor-lock state. We only rotate the camera while locked,
        // so releasing the cursor with LAlt pauses look input without losing
        // keyboard movement.
        bool cursorLocked = false;

        // Coordinates of an outstanding SDL_WarpMouseInWindow target. The
        // synth motion event SDL fires in response to a warp lands at the
        // BACK of the queue, behind any user motion events that were already
        // pending. A naive "eat the next motion event" filter therefore
        // drops a real user motion and lets the warp synth through with its
        // wrong-direction delta — exactly what causes look-stutter when the
        // user moves the mouse fast. We instead match the synth event by
        // its absolute position (event.x/event.y == warpPendingX/Y) so we
        // ignore the right event no matter where it sits in the queue.
        // -1 means "no warp pending".
        int warpPendingX = -1;
        int warpPendingY = -1;

        // True when running inside WSL/WSLg. In that environment
        // SDL_WarpMouseInWindow is effectively a no-op (the authoritative
        // cursor lives on the Windows host), so no "ghost" motion event is
        // ever generated by the warp. We therefore must NOT arm
        // ignoreNextMotion on WSL — doing so would eat a real user motion
        // event instead, corrupting the delta stream. Detected once at
        // construction via WSL_INTEROP / WSL_DISTRO_NAME env vars.
        bool onWSL = false;
    };
}
