name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc
            cc: gcc
            cxx: g++
          - os: ubuntu-latest
            compiler: clang
            cc: clang
            cxx: clang++
          - os: windows-latest
            compiler: msvc
            cc: cl
            cxx: cl
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup vcpkg (if you use it for SDL2/GLEW/etc.)
        if: matrix.os == 'windows-latest'
        run: |
          # (optional) install SDL2, GLEW, etc via vcpkg here, if you prefer.

      - name: Install prerequisites (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake ccache

      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ matrix.compiler }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ matrix.compiler }}-

      - name: Cache CMake build directory
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-cmake-${{ matrix.compiler }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-${{ matrix.compiler }}-

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake \
            -DCMAKE_C_COMPILER=${{ matrix.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
            -DCMAKE_BUILD_TYPE=Release \
            ..

      - name: Build
        run: cmake --build build --config Release -- -j$(nproc || echo 2)

      - name: Run unit tests
        run: |
          cd build
          ctest --output-on-failure --parallel $(nproc || echo 2)
        continue-on-error: false

      - name: Upload test logs on failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: ctest-logs-${{ matrix.os }}-${{ matrix.compiler }}
          path: build/Testing/**/Test.xml
